adminactions/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import format_date

urlpatterns = (
    url(r'^s/format/date/$', format_date, name='adminactions.format_date'),
)

main/urls.py
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    
]

potpaladrvocumur/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    re_path(r'^adminactions/', include('adminactions.urls')),
]

adminactions/models.py
# -*- coding: utf-8 -*-
from django.apps import apps
from django.db.models.signals import post_migrate


def get_permission_codename(action, opts):
    return '%s_%s' % (action, opts.object_name.lower())


# def get_models(a=None):
#     """Handles deprecation of django.db.models.loading in Django1.9"""
#
#     from django.apps import apps  # noqa
#     return apps.get_models()
#     # return [m for m in apps.get_models()]


def create_extra_permission(sender, **kwargs):
    from django.contrib.auth.models import Permission
    from django.contrib.contenttypes.models import ContentType
    for model in apps.get_models():
        for action in ('adminactions_export', 'adminactions_massupdate',
                       'adminactions_merge', 'adminactions_chart',
                       'adminactions_byrowsupdate'):
            opts = model._meta
            codename = get_permission_codename(action, opts)
            label = 'Can {} {} (adminactions)'.format(action.replace('adminactions_', ""),
                                                      opts.verbose_name_raw)
            ct = ContentType.objects.get_for_model(model)
            params = dict(codename=codename,
                          content_type=ct,
                          defaults={'name': label[:50]})
            p, __ = Permission.objects.get_or_create(**params)
    post_migrate.disconnect(dispatch_uid='adminactions.create_extra_permission')


post_migrate.connect(create_extra_permission,
                     dispatch_uid='adminactions.create_extra_permission')

adminactions/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms.models import ModelForm
from django.forms.widgets import SelectMultiple
from django.utils import formats
from django.utils.translation import gettext_lazy as _

from .api import csv, delimiters, quotes


class GenericActionForm(ModelForm):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)
    select_across = forms.BooleanField(label='', required=False, initial=0,
                                       widget=forms.HiddenInput({'class': 'select-across'}))
    action = forms.CharField(label='', required=True, initial='', widget=forms.HiddenInput())

    def configured_fields(self):
        return [field for field in self if not field.is_hidden and field.name.startswith('_')]

    def model_fields(self):
        """
        Returns a list of BoundField objects that aren't "private" fields.
        """
        return [field for field in self if
                not (field.name.startswith('_') or field.name in ['select_across', 'action'])]


class CSVOptions(forms.Form):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)
    select_across = forms.BooleanField(label='', required=False, initial=0,
                                       widget=forms.HiddenInput({'class': 'select-across'}))
    action = forms.CharField(label='', required=True, initial='', widget=forms.HiddenInput())

    header = forms.BooleanField(label=_('Header'), required=False)
    delimiter = forms.ChoiceField(label=_('Delimiter'), choices=list(zip(delimiters, delimiters)), initial=',')
    quotechar = forms.ChoiceField(label=_('Quotechar'), choices=list(zip(quotes, quotes)), initial="'")
    quoting = forms.ChoiceField(
        label=_('Quoting'),
        choices=((csv.QUOTE_ALL, _('All')),
                 (csv.QUOTE_MINIMAL, _('Minimal')),
                 (csv.QUOTE_NONE, _('None')),
                 (csv.QUOTE_NONNUMERIC, _('Non Numeric'))), initial=csv.QUOTE_ALL)

    escapechar = forms.ChoiceField(label=_('Escapechar'), choices=(('', ''), ('\\', '\\')), required=False)
    datetime_format = forms.CharField(label=_('Datetime format'), initial=formats.get_format('DATETIME_FORMAT'))
    date_format = forms.CharField(label=_('Date format'), initial=formats.get_format('DATE_FORMAT'))
    time_format = forms.CharField(label=_('Time format'), initial=formats.get_format('TIME_FORMAT'))
    columns = forms.MultipleChoiceField(label=_('Columns'), widget=SelectMultiple(attrs={'size': 20}))


class XLSOptions(forms.Form):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)
    select_across = forms.BooleanField(label='', required=False, initial=0,
                                       widget=forms.HiddenInput({'class': 'select-across'}))
    action = forms.CharField(label='', required=True, initial='', widget=forms.HiddenInput())

    header = forms.BooleanField(label=_('Header'), required=False)
    use_display = forms.BooleanField(label=_('Use display'), required=False)
    # delimiter = forms.ChoiceField(choices=zip(delimiters, delimiters), initial=',')
    # quotechar = forms.ChoiceField(choices=zip(quotes, quotes), initial="'")
    # quoting = forms.ChoiceField(
    #     choices=((csv.QUOTE_ALL, 'All'),
    #              (csv.QUOTE_MINIMAL, 'Minimal'),
    #              (csv.QUOTE_NONE, 'None'),
    #              (csv.QUOTE_NONNUMERIC, 'Non Numeric')), initial=csv.QUOTE_ALL)
    #
    # escapechar = forms.ChoiceField(choices=(('', ''), ('\\', '\\')), required=False)
    # datetime_format = forms.CharField(initial=formats.get_format('DATETIME_FORMAT'))
    # date_format = forms.CharField(initial=formats.get_format('DATE_FORMAT'))
    # time_format = forms.CharField(initial=formats.get_format('TIME_FORMAT'))
    columns = forms.MultipleChoiceField(label=_('Columns'), widget=SelectMultiple(attrs={'size': 20}))

adminactions/views.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.http import HttpResponse
from django.utils import dateformat


def format_date(request):
    d = datetime.now()
    return HttpResponse(dateformat.format(d, request.GET.get('fmt', '')))

adminactions/templates/adminactions/any_model.html
{% extends "admin/change_form.html" %}
{% load i18n admin_modify adminmedia static %}
{% block extrahead %}{{ block.super }}
    <style type="text/css">
        #col1 {
            float: left;
            width: 70%;
        }

        #col2 {
            float: right;
            width: 30%;
        }
        #col2 select {
            width: 100%;
        }
    </style>
    <script language="javascript" type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    <script language="javascript" type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
    <script language="javascript" type="text/javascript" src="{% static 'adminactions/js/massupdate.js' %}"></script>
    <!--<script language="javascript" type="text/javascript" src="/media/js/admin/DateTimeShortcuts.js"></script>-->
{% endblock %}

{% block breadcrumbs %}{% if not is_popup %}
    <div class="breadcrumbs">
        <a href="../../../">{% trans "Home" %}</a> &rsaquo;
        <a href="../../">{{ app_label|capfirst|escape }}</a> &rsaquo;
        <a href="../">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
        Mass Update
    </div>
{% endif %}{% endblock %}

{% block content %}
    {% if form.subject.errors %}
        <ol>
            {% for error in form.subject.errors %}
                <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
        </ol>
    {% endif %}

    <div id='col1'>
        <form action="../" method="post">
            {% csrf_token %}
            <table>
                {% for field in adminform.form.configured_fields %}
                    <tr>
                        <td>{% if field.field.required %}
                            <b>{% endif %} {{ field.label_tag }}{% if field.field.required %}</b>{% endif %}  </td>
                        <td colspan="3">
                            {{ field.errors }}
                            {{ field }}&nbsp;<span class="help">{{ field.help_text }}</span>
                        </td>
                    </tr>
                {% endfor %}
                <tr><td colspan="4"><hr/></td></tr>
                <tr><th>field name </th><th>update</th><th>new value</th><th>existing values <small><i>(some of the most used )</i></small></th></tr>
                {% for field in adminform.form.model_fields %}
                    <tr class="{{ field.name }}-row">
                        <td>{% if field.field.required %}
                            <b>{% endif %} {{ field.label_tag }}{% if field.field.required %}</b>{% endif %}  </td>
                        <td class='col_enabler'><input type="checkbox" name="chk_id_{{ field.name }}" class="enabler"></td>
                        <td class='col_field field-{{ field.name }}-value'>{{ field.errors }}
                            {{ field }}&nbsp;</td>
                        </td>

                    </tr>
                {% endfor %}
            </table>
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            <input type="hidden" name="action" value="{{ action }}"/>
            <input type="submit" name="apply" value="Update records"/>
        </form>
    </div>
    <div id='col2'>
        Selected records:
        <select size="30">
            {% for el in selection %}
                <option>{{ el }}</option>
            {% endfor %}
        </select>


    </div>
{% endblock %}

adminactions/templates/adminactions/byrows_update.html
{% extends "admin/change_form.html" %}
{% load i18n admin_modify actions static %}
{% block extrahead %}{{ block.super }}
    <style type="text/css">
        .formset-container {
            overflow: auto;
            margin: 1em auto
        }
	input.readonly, select.readonly {
	    border: 0;
	    background: transparent;
	}
    </style>
    <script language="javascript" type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    <script language="javascript" type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}{% if not is_popup %}
    <div class="breadcrumbs">
        <a href="../../">{% trans "Home" %}</a> &rsaquo;
        <a href="../">{{ app_label|capfirst|escape }}</a> &rsaquo;
        <a href=".">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
        {{ action_short_description|capfirst }}
    </div>
{% endif %}{% endblock %}

{% block content %}
    {% if formset.errors %}
        <p class="errornote">
            {% if formset.errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
        </p>
        {{ adminform.form.non_field_errors }}
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{ formset.non_form_errors.as_ul }}
        <div class="formset-container">
            <table id="formset" class="form">
                {% for form in formset.forms %}
                {% if forloop.first %}
                <thead>
                    <tr>
                        {% for field in form.visible_fields %}
                        <th><label class="{% if field.field.required %}required{% endif %}">{{ field.label|capfirst }}</label></th>
                        {% endfor %}
                    </tr>
                </thead>
                {% endif %}
                <tr class="row {% cycle 'row1' 'row2' %}">
                    {% for field in form.visible_fields %}
                    <td>
                        {# Include the hidden fields in the form #}
                        {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                        {% endif %}
                        {{ field.errors.as_ul }}
                        {{ field }}
                    </td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
        </div>
        {{ formset.management_form }}
        {% for hidden in actionform.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <input type="submit" name="apply" value="Update records"/>
    </form>
{% endblock %}

adminactions/templates/adminactions/charts.html
{% extends "admin/change_form.html" %}{% load i18n static admin_modify admin_urls %}{% load url from aa_compat %}
{% block extrahead %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'adminactions/js/jqplot/jquery.jqplot.min.css' %}"/>
    <script>(function ($) {
        jQuery = $.noConflict(true);
    })(django.jQuery);</script>
    <script type="text/javascript" src="{% static 'adminactions/js/jqplot/jquery.jqplot.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'adminactions/js/jqplot/plugins/jqplot.pieRenderer.js' %}"></script>
    <script type="text/javascript" src="{% static 'adminactions/js/jqplot/plugins/jqplot.barRenderer.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'adminactions/js/jqplot/plugins/jqplot.categoryAxisRenderer.min.js' %}"></script>


{% endblock %}

{% block breadcrumbs %}{% if not is_popup %}
    <div class="breadcrumbs">
        <a href="../../">{% trans "Home" %}</a> &rsaquo;
        <a href="../">{{ app_label|capfirst|escape }}</a> &rsaquo;
        <a href=".">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
	{{ action_short_description|capfirst }}
    </div>
{% endif %}
{% endblock %}

{% block content %}
    <div class="left">
        <form action="." method="post">-{% csrf_token %}=
            <table>
                {{ adminform.form }}
            </table>
            <input type="hidden" name="action" value="{{ action }}"/>
            <input type="submit" name="apply" value="go"/>
        </form>
    </div>
    {% if graph_type %}
        <div id="chart_div2" class='left'></div>
        <div id="chart_div" style="height:300px; width:800px;"></div>
    {% endif %}
    <script type="text/javascript">
        {%  if graph_type %}
            (function ($) {
                var plot1 = $.jqplot('chart_div', {{ as_json|safe }}, {{ extra|safe }});
            })(django.jQuery);
        {% endif %}
    </script>
{% endblock %}

adminactions/templates/adminactions/export_csv.html
{% extends "admin/change_form.html" %}
{% load i18n admin_modify admin_urls %}{% load url from aa_compat %}
{% block extrahead %}{{ block.super }}
    <style type="text/css">
        #form {
            float: left;
            width: 40%;
        }

        #legend {
            float: left;
            width: 60%;
        }
    </style>
    {% url 'adminactions.format_date' as url_format_date %}
    {% if url_format_date %}
    <script type="text/javascript">
        (function ($) {
            $(document).ready(function ($) {
{#                $('#id_datetime_format, #id_date_format, #id_time_format,').after('&nbsp;&nbsp;<span class="sample"></span>');#}
                var _url = "{{ url_format_date }}";
                var get_format = function (sender) {
                    $.get(_url, {'fmt':$(sender).val()},
                            function (data) {
                                $(sender).next('.sample').html(data);
                            }
                    );
                };
                $('#id_datetime_format, #id_date_format, #id_time_format').after('&nbsp;&nbsp;<span class="sample"></span>').keyup(function () {
                    clearTimeout($(this).data('timer'));
                    var target = $(this);
                    var wait = setTimeout(function () {
                        get_format(target)
                    }, 500);
                    $(this).data('timer', wait);
                }).trigger('keyup');
            });
        })(django.jQuery);

    </script>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}{% if not is_popup %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% trans "Home" %}</a> &rsaquo;
        <a href="{% url 'admin:index' %}{{ app_label}}">{{ app_label|capfirst }}</a> &rsaquo;
        {% if has_change_permission %}<a
                href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %} &rsaquo;
	{{ action_short_description|capfirst }}
    </div>
{% endif %}{% endblock %}

{% block content %}
    {% if adminform.form.subject.errors %}
        <ol>
            {% for error in adminform.form.subject.errors %}
                <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
        </ol>
    {% endif %}
    <div id='form'>
        <form action="" method="post">
            {% csrf_token %}
            <table>
                {{ adminform.form }}
            </table>
{#            <input type="hidden" name="action" value="{{ action }}"/>#}
            <input type="submit" name="apply" value="{% trans 'Export' %}"/>
        </form>
    </div>
    {% url 'adminactions.format_date' as url_format_date %}
    {% if url_format_date %}
    <div id='legend-date'>
    <table xmlns="http://www.w3.org/1999/xhtml" lass="doctable table">
    <caption><b>The following characters are recognized in the
        <i><tt class="parameter">format</tt></i> parameter string</b></caption>

    <thead valign="middle">
    <tr valign="middle">
        <th><i><tt class="parameter">format</tt></i> character</th>

        <th>Description</th>
        <th>Example returned values</th>
    </tr>

    </thead>

    <tbody valign="middle" class="tbody">
    <tr valign="middle">
        <td align="center"><em class="emphasis">Day</em></td>

        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>d</i></td>
        <td align="left">Day of the month, 2 digits with leading zeros</td>

        <td align="left"><i>01</i> to <i>31</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>D</i></td>
        <td align="left">A textual representation of a day, three letters</td>

        <td align="left"><i>Mon</i> through <i>Sun</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>j</i></td>
        <td align="left">Day of the month without leading zeros</td>

        <td align="left"><i>1</i> to <i>31</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>l</i> (lowercase 'L')</td>
        <td align="left">A full textual representation of the day of the week</td>

        <td align="left"><i>Sunday</i> through <i>Saturday</i></td>
    </tr>
    <tr>
    <td align="left"><i>1</i> (for Monday) through <i>7</i> (for Sunday)</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>S</i></td>
        <td align="left">English ordinal suffix for the day of the month, 2 characters</td>

        <td align="left">
            <i>st</i>, <i>nd</i>, <i>rd</i> or
            <i>th</i>. Works well with <i>j</i>
        </td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>w</i></td>
        <td align="left">Numeric representation of the day of the week</td>
        <td align="left"><i>0</i> (for Sunday) through <i>6</i> (for Saturday)</td>

    </tr>

    <tr valign="middle">
        <td align="left"><i>z</i></td>
        <td align="left">The day of the year (starting from 0)</td>
        <td align="left"><i>0</i> through <i>365</i></td>

    </tr>

    <tr valign="middle">
        <td align="center"><em class="emphasis">Week</em></td>
        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>W</i></td>
        <td align="left">ISO-8601 week number of year, weeks starting on Monday (added in PHP 4.1.0)</td>
        <td align="left">Example: <i>42</i> (the 42nd week in the year)</td>
    </tr>

    <tr valign="middle">
        <td align="center"><em class="emphasis">Month</em></td>
        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>F</i></td>

        <td align="left">A full textual representation of a month, such as January or March</td>
        <td align="left"><i>January</i> through <i>December</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>m</i></td>

        <td align="left">Numeric representation of a month, with leading zeros</td>
        <td align="left"><i>01</i> through <i>12</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>M</i></td>

        <td align="left">A short textual representation of a month, three letters</td>
        <td align="left"><i>Jan</i> through <i>Dec</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>n</i></td>

        <td align="left">Numeric representation of a month, without leading zeros</td>
        <td align="left"><i>1</i> through <i>12</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>t</i></td>

        <td align="left">Number of days in the given month</td>
        <td align="left"><i>28</i> through <i>31</i></td>
    </tr>

    <tr valign="middle">
        <td align="center"><em class="emphasis">Year</em></td>

        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>L</i></td>
        <td align="left">Whether it's a leap year</td>

        <td align="left"><i>1</i> if it is a leap year, <i>0</i> otherwise.</td>
    </tr>

    {#              <tr valign="middle">#}
    {#               <td align="left"><i>o</i></td>#}
    {#               <td align="left">ISO-8601 year number. This has the same value as#}
    {#                <i>Y</i>, except that if the ISO week number#}
    {#                (<i>W</i>) belongs to the previous or next year, that year#}
    {#                is used instead. (added in PHP 5.1.0)</td>#}

    <td align="left">Examples: <i>1999</i> or <i>2003</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>Y</i></td>
        <td align="left">A full numeric representation of a year, 4 digits</td>

        <td align="left">Examples: <i>1999</i> or <i>2003</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>y</i></td>
        <td align="left">A two digit representation of a year</td>

        <td align="left">Examples: <i>99</i> or <i>03</i></td>
    </tr>

    <tr valign="middle">
        <td align="center"><em class="emphasis">Time</em></td>
        <td align="left">---</td>

        <td align="left">---</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>a</i></td>
        <td align="left">Lowercase Ante meridiem and Post meridiem</td>
        <td align="left"><i>am</i> or <i>pm</i></td>

    </tr>

    <tr valign="middle">
        <td align="left"><i>A</i></td>
        <td align="left">Uppercase Ante meridiem and Post meridiem</td>
        <td align="left"><i>AM</i> or <i>PM</i></td>

    </tr>

    <tr valign="middle">
        <td align="left"><i>B</i></td>
        <td align="left">Swatch Internet time</td>
        <td align="left"><i>000</i> through <i>999</i></td>

    </tr>

    <tr valign="middle">
        <td align="left"><i>g</i></td>
        <td align="left">12-hour format of an hour without leading zeros</td>
        <td align="left"><i>1</i> through <i>12</i></td>

    </tr>

    <tr valign="middle">
        <td align="left"><i>G</i></td>
        <td align="left">24-hour format of an hour without leading zeros</td>
        <td align="left"><i>0</i> through <i>23</i></td>

    </tr>

    <tr valign="middle">
        <td align="left"><i>h</i></td>
        <td align="left">12-hour format of an hour with leading zeros</td>
        <td align="left"><i>01</i> through <i>12</i></td>

    </tr>

    <tr valign="middle">
        <td align="left"><i>H</i></td>
        <td align="left">24-hour format of an hour with leading zeros</td>
        <td align="left"><i>00</i> through <i>23</i></td>

    </tr>

    <tr valign="middle">
        <td align="left"><i>i</i></td>
        <td align="left">Minutes with leading zeros</td>
        <td align="left"><i>00</i> to <i>59</i></td>

    </tr>

    <tr valign="middle">
        <td align="left"><i>s</i></td>
        <td align="left">Seconds, with leading zeros</td>
        <td align="left"><i>00</i> through <i>59</i></td>

    </tr>

    {#              <tr valign="middle">#}
    {#               <td align="left"><i>u</i></td>#}
    {#               <td align="left">Microseconds (added in PHP 5.2.2)</td>#}
    {#               <td align="left">Example: <i>654321</i></td>#}
    {#              </tr>#}

    <tr valign="middle">
        <td align="center"><em class="emphasis">Timezone</em></td>
        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    {#              <tr valign="middle">#}
    {##}
    {#               <td align="left"><i>e</i></td>#}
    {#               <td align="left">Timezone identifier (added in PHP 5.1.0)</td>#}
    {#               <td align="left">Examples: <i>UTC</i>, <i>GMT</i>, <i>Atlantic/Azores</i></td>#}
    {#              </tr>#}

    <tr valign="middle">
        <td align="left"><i>I</i> (capital i)</td>
        <td align="left">Whether or not the date is in daylight saving time</td>
        <td align="left"><i>1</i> if Daylight Saving Time, <i>0</i> otherwise.</td>

    </tr>

    <tr valign="middle">
        <td align="left"><i>O</i></td>
        <td align="left">Difference to Greenwich time (GMT) in hours</td>
        <td align="left">Example: <i>+0200</i></td>
    </tr>

    {#              <tr valign="middle">#}
    {#               <td align="left"><i>P</i></td>#}
    {#               <td align="left">Difference to Greenwich time (GMT) with colon between hours and minutes (added in PHP 5.1.3)</td>#}
    {#               <td align="left">Example: <i>+02:00</i></td>#}
    {#              </tr>#}

    <tr valign="middle">

        <td align="left"><i>T</i></td>
        <td align="left">Timezone abbreviation</td>
        <td align="left">Examples: <i>EST</i>, <i>MDT</i> ...</td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>Z</i></td>
        <td align="left">Timezone offset in seconds. The offset for timezones west of UTC is always
            negative, and for those east of UTC is always positive.
        </td>
        <td align="left"><i>-43200</i> through <i>50400</i></td>
    </tr>

    <tr valign="middle">
        <td align="center"><em class="emphasis">Full Date/Time</em></td>
        <td align="left">---</td>
        <td align="left">---</td>
    </tr>

    {#              <tr valign="middle">#}
    {#               <td align="left"><i>c</i></td>#}
    {##}
    {#               <td align="left">ISO 8601 date (added in PHP 5)</td>#}
    {#               <td align="left">2004-02-12T15:19:21+00:00</td>#}
    {#              </tr>#}

    <tr valign="middle">
        <td align="left"><i>r</i></td>
        <td align="left"><a class="link external" href="http://www.faqs.org/rfcs/rfc2822">» RFC 2822</a> formatted date
        </td>

        <td align="left">Example: <i>Thu, 21 Dec 2000 16:01:07 +0200</i></td>
    </tr>

    <tr valign="middle">
        <td align="left"><i>U</i></td>
        <td align="left">Seconds since the Unix Epoch (January 1 1970 00:00:00 GMT)</td>
        <td align="left">See also <span class="function"><a class="function" href="function.time.php">time()</a></span>
        </td>

    </tr>

    </tbody>

    </table>

    </div>
    {% endif  %}
{% endblock %}

adminactions/templates/adminactions/export_fixture.html
{% extends "admin/change_form.html" %}
{% load i18n admin_modify admin_urls %}{% load url from aa_compat %}

{% block breadcrumbs %}{% if not is_popup %}
    <div class="breadcrumbs">
        <a href="../../">{% trans "Home" %}</a> &rsaquo;
        <a href="../">{{ app_label|capfirst|escape }}</a> &rsaquo;
        <a href=".">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
	{{ action_short_description|capfirst }}
    </div>
{% endif %}{% endblock %}

{% block content %}
    {% if form.subject.errors %}
        <ol>
            {% for error in form.subject.errors %}
                <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
        </ol>
    {% endif %}
    {{ data }}
    <div id='form'>
        <form method="post">
            {% csrf_token %}
            <table>
                {{ adminform.form }}
            </table>
            <input type="submit" name="apply" value="Export"/>
        </form>
    </div>
    </div>
{% endblock %}